# -*- coding: utf-8 -*-

from ..Parse import (
	ParseBoolean,
	ParseString,
	ParseStringWithParameters,
	ParseInteger,
	ParseFloat,
	ParseDate,
	ParseParameter,
	ParseParameters,
	ParseList,
)
from .Common import (
	Accept,
	ParseAccept,
	AcceptEncoding,
	ParseAcceptEncoding,
	RequestCacheControl,
	ParseRequestCacheControl,
	KeepAlive,
	ParseKeepAlive,
	Link,
	ParseLink,
	Priority,
	ParsePriority,
	Upgrade,
	ParseUpgrade,
	Via,
	ParseVia,	
	Warning,
	ParseWarning,
)
from .Content import (
	ContentRange,
	ParseContentRange,
	ContentType,
	ParseContentType,
	ETag,
	ParseETag,
)
from .Request import (
	AcceptLanguage,
	ParseAcceptLanguage,
	AltUsed,
	ParseAltUsed,
	Authorization,
	ParseAuthorization,
	Cookie,
	ParseCookie,
	ParseIfRange,
	ProxyAuthorization,
	ParseProxyAuthorization,
	Range,
	ParseRange,
	SecCHUA,
	ParseSecCHUA,
	SecCHUAFullVersion,
	ParseSecCHUAFullVersion,
	TE,
	ParseTE,
)

from typing import Any

__all__ = (
	'ToENV',
	'ToHeader',
	'ParseRequestHeader',
)

def ToENV(key: str) -> str:
	return {
		'Accept': 'ACCEPT',
		'Accept-CH': 'ACCEPT_CH',
		'Accept-Encoding': 'ACCEPT_ENCODING',
		'Accept-Language': 'ACCEPT_LANGUAGE',
		'Accept-Patch': 'ACCEPT_PATCH',
		'Accept-Post': 'ACCEPT_POST',
		'Accept-Range': 'ACCEPT_RANGE',
		'Access-Control-Allow-Credentials': 'ACCESS_CONTROL_ALLOW_CREDENTIALS',
		'Access-Control-Allow-Headers': 'ACCESS_CONTROL_ALLOW_HEADERS',
		'Access-Control-Allow-Methods': 'ACCESS_CONTROL_ALLOW_METHODS',
		'Access-Control-Allow-Origin': 'ACCESS_CONTROL_ALLOW_ORIGIN',
		'Access-Control-Expose-Headers': 'ACCESS_CONTROL_EXPOSE_HEADERS',
		'Access-Control-Max-Age': 'ACCESS_CONTROL_MAX_AGE',
		'Access-Control-Request-Headers': 'ACCESS_CONTROL_REQUEST_HEADERS',
		'Access-Control-Request-Method': 'ACCESS_CONTROL_REQUEST_METHOD',
		'Age': 'AGE',
		'Allow': 'ALLOW',
		'Alt-Svc': 'ALT_SVC',
		'Alt-Used': 'ALT_USED',
		'Attribution-Reporting-Eligible': 'ATTRIBUTION_REPORTING_ELIGIBLE',
		'Attribution-Reporting-Register-Source': 'ATTRIBUTION_REPORTING_REGISTER_SOURCE',
		'Attribution-Reporting-Trigger': 'ATTRIBUTION_REPORTING_TRIGGER',
		'Authorization': 'AUTHORIZATION',
		'Cache-Control': 'CACHE_CONTROL',
		'Clear-Site-Data': 'CLEAR_SITE_DATA',
		'Connection': 'CONNECTION',
		'Content-Digest': 'CONTENT_DIGEST',
		'Content-Disposition': 'CONTENT_DISPOSITION',
		'Content-DPR': 'CONTENT_DPR',
		'Content-Encoding': 'CONTENT_ENCODING',
		'Content-Language': 'CONTENT_LANGUAGE',
		'Content-Length': 'CONTENT_LENGTH',
		'Content-Location': 'CONTENT_LOCATION',
		'Content-Range': 'CONTENT_RANGE',
		'Content-Security-Policy': 'CONTENT_SECURITY_POLICY',
		'Content-Security-Policy-Report-Only': 'CONTENT_SECURITY_POLICY_REPORT_ONLY',
		'Content-Type': 'CONTENT_TYPE',
		'Cookie': 'COOKIE',
		'Critical-CH': 'CRITICAL_CH',
		'Cross-Origin-Embedder-Policy': 'CROSS_ORIGIN_EMBEDDER_POLICY',
		'Cross-Origin-Opener-Policy': 'CROSS_ORIGIN_OPENER_POLICY',
		'Cross-Origin-Resource-Policy': 'CROSS_ORIGIN_RESOURCE_POLICY',
		'Date': 'DATE',
		'Device-Memory': 'DEVICE_MEMORY',
		'DNT': 'DNT',
		'Downlink': 'DOWNLINK',
		'DPR': 'DPR',
		'Early-Data': 'EARLY_DATA',
		'ECT': 'ECT',
		'ETag': 'ETAG',
		'Expect': 'EXPECT',
		'Expect-CT': 'EXPECT_CT',
		'Expires': 'EXPIRES',
		'Forwarded': 'FORWARDED',
		'From': 'FROM',
		'Host': 'HOST',
		'If-Match': 'IF_MATCH',
		'If-Modified-Since': 'IF_MODIFIED_SINCE',
		'If-Not-Match': 'IF_NOT_MATCH',
		'If-Range': 'IF_RANGE',
		'If-Unmodified-Since': 'IF_UNMODIFIED_SINCE',
		'Keep-Alive': 'KEEP_ALIVE',
		'Last-Modified': 'LAST_MODIFIED',
		'Link': 'LINK',
		'Location': 'LOCATION',
		'Max-Forwards': 'MAX_FORWARDS',
		'NEL': 'NEL',
		'No-Vary-Search': 'NO_VARY_SEARCH',
		'Observe-Browsing-Topics': 'OBSERVE_BROWSING_TOPICS',
		'Origin': 'ORIGIN',
		'Origin-Agent-Cluster': 'ORIGIN_AGENT_CLUSTER',
		'Permission-Policy': 'PERMISSION_POLICY',
		'Pragma': 'PRAGMA',
		'Priority': 'PRIORITY',
		'Proxy-Authenticate': 'PROXY_AUTHENTICATE',
		'Proxy-Authorization': 'PROXY_AUTHORIZATION',
		'Range': 'RANGE',
		'Referer': 'REFERER',
		'Referer-Policy': 'REFERER_POLICY',
		'Refresh': 'REFRESH',
		'Report-To': 'REPORT_TO',
		'Reporting-Endpoint': 'REPORTING_ENDPOINT',
		'Repr-Digest': 'REPR_DIGEST',
		'Retry-After': 'RETRY_AFTER',
		'RTT': 'RTT',
		'Save-Data': 'SAVE_DATA',
		'Sec-Browsing-Topics': 'SEC_BROWSING_TOPICS',
		'Sec-CH-Prefers-Color-Scheme': 'SEC_CH_PREFERS_COLOR_SCHEME',
		'Sec-CH-Prefers-Reduced-Motion': 'SEC_CH_PREFERS_REDUCED_MOTION',
		'Sec-CH-Prefers-Reduced-Transparency': 'SEC_CH_PREFERS_REDUCED_TRANSPARENCY',
		'Sec-CH-UA': 'SEC_CH_UA',
		'Sec-CH-UA-Arch': 'SEC_CH_UA_ARCH',
		'Sec-CH-UA-Bitness': 'SEC_CH_UA_BITNESS',
		'Sec-CH-UA-Full-Version': 'SEC_CH_UA_FULL_VERSION',
		'Sec-CH-UA-Mobile': 'SEC_CH_UA_MOBILE',
		'Sec-CH-UA-Model': 'SEC_CH_UA_MODEL',
		'Sec-CH-UA-Platform': 'SEC_CH_UA_PLATFORM',
		'Sec-CH-UA-Platform-Version': 'SEC_CH_UA_PLATFORM_VERSION',
		'Sec-Fetch-Dest': 'SEC_FETCH_DEST',
		'Sec-Fetch-Mode': 'SEC_FETCH_MODE',
		'Sec-Fetch-Site': 'SEC_FETCH_SITE',
		'Sec-Fetch-User': 'SEC_FETCH_USER',
		'Sec-GPC': 'SEC_GPC',
		'Sec-Purpose': 'SEC_PURPOSE',
		'Sec-WebSocket-Accept': 'SEC_WEBSOCKET_ACCEPT',
		'Sec-WebSocket-Extensions': 'SEC_WEBSOCKET_EXTENSIONS',
		'Sec-WebSocket-Key': 'SEC_WEBSOCKET_KEY',
		'Sec-WebSocket-Protocol': 'SEC_WEBSOCKET_PROTOCOL',
		'Sec-WebSocket-Version': 'SEC_WEBSOCKET_VERSION',
		'Server': 'SERVER',
		'Server-Timing': 'SERVER_TIMING',
		'Service-Worker': 'SERVICE_WORKER',
		'Service-Worker-Allowed': 'SERVICE_WORKER_ALLOWED',
		'Service-Worker-Navigation-Prelaod': 'SERVICE_WORKER_NAVIGATION_PRELAOD',
		'Set-Cookie': 'SET_COOKIE',
		'Set-Login': 'SET_LOGIN',
		'SourceMap': 'SOURCEMAP',
		'Speculation-Rules': 'SPECULATION_RULES',
		'Strict-Transport-Security': 'STRICT_TRANSPORT_SECURITY',
		'Supports-Loading-Mode': 'SUPPORTS_LOADING_MODE',
		'TE': 'TE',
		'Timing-Allow-Origin': 'TIMING_ALLOW_ORIGIN',
		'Tk': 'TK',
		'Trailer': 'TRAILER',
		'Transfer-Encoding': 'TRANSFER_ENCODING',
		'Upgrade': 'UPGRADE',
		'Upgrade-Insecure-Requests': 'UPGRADE_INSECURE_REQUESTS',
		'User-Agent': 'USER_AGENT',
		'Vary': 'VARY',
		'Via': 'VIA',
		'Viewport-Width': 'VIEWPORT_WIDTH',
		'Want-Content-Digest': 'WANT_CONTENT_DIGEST',
		'Want-Repr-Digest': 'WANT_REPR_DIGEST',
		'Warning': 'WARNING',
		'Width': 'WIDTH',
		'WWW-Authenticate': 'WWW_AUTHENTICATE',
		'X-Content-Type-Options': 'X_CONTENT_TYPE_OPTIONS',
		'X-DNS-Prefetch-Control': 'X_DNS_PREFETCH_CONTROL',
		'X-Forwarded-For': 'X_FORWARDED_FOR',
		'X-Forwarded-Host': 'X_FORWARDED_HOST',
		'X-Forwarded-Proto': 'X_FORWARDED_PROTO',
		'X-Frame-Options': 'X_FRAME_OPTIONS',
		'X-Permitted-Cross-Domain-Policies': 'X_PERMITTED_CROSS_DOMAIN_POLICIES',
		'X-Powered-By': 'X_POWERED_BY',
		'X-Robots-Tag': 'X_ROBOTS_TAG',
		'X-XSS-Protection': 'X_XSS_PROTECTION',
	}.get(key, key.replace('-', '_').upper()) # TODO : replace cases


def ToHeader(key: str) -> str:
	return {
		'ACCEPT': 'Accept',
		'ACCEPT_CH': 'Accept-CH',
		'ACCEPT_ENCODING': 'Accept-Encoding',
		'ACCEPT_LANGUAGE': 'Accept-Language',
		'ACCEPT_PATCH': 'Accept-Patch',
		'ACCEPT_POST': 'Accept-Post',
		'ACCEPT_RANGE': 'Accept-Range',
		'ACCESS_CONTROL_ALLOW_CREDENTIALS': 'Access-Control-Allow-Credentials',
		'ACCESS_CONTROL_ALLOW_HEADERS': 'Access-Control-Allow-Headers',
		'ACCESS_CONTROL_ALLOW_METHODS': 'Access-Control-Allow-Methods',
		'ACCESS_CONTROL_ALLOW_ORIGIN': 'Access-Control-Allow-Origin',
		'ACCESS_CONTROL_EXPOSE_HEADERS': 'Access-Control-Expose-Headers',
		'ACCESS_CONTROL_MAX_AGE': 'Access-Control-Max-Age',
		'ACCESS_CONTROL_REQUEST_HEADERS': 'Access-Control-Request-Headers',
		'ACCESS_CONTROL_REQUEST_METHOD': 'Access-Control-Request-Method',
		'AGE': 'Age',
		'ALLOW': 'Allow',
		'ALT_SVC': 'Alt-Svc',
		'ALT_USED': 'Alt-Used',
		'ATTRIBUTION_REPORTING_ELIGIBLE': 'Attribution-Reporting-Eligible',
		'ATTRIBUTION_REPORTING_REGISTER_SOURCE': 'Attribution-Reporting-Register-Source',
		'ATTRIBUTION_REPORTING_TRIGGER': 'Attribution-Reporting-Trigger',
		'AUTHORIZATION': 'Authorization',
		'CACHE_CONTROL': 'Cache-Control',
		'CLEAR_SITE_DATA': 'Clear-Site-Data',
		'CONNECTION': 'Connection',
		'CONTENT_DIGEST': 'Content-Digest',
		'CONTENT_DISPOSITION': 'Content-Disposision',
		'CONTENT_DPR': 'Content-DPR',
		'CONTENT_ENCODING': 'Content-Encoding',
		'CONTENT_LANGUAGE': 'Content-Language',
		'CONTENT_LENGTH': 'Content-Length',
		'CONTENT_LOCATION': 'Content-Location',
		'CONTENT_RANGE': 'Content-Range',
		'CONTENT_SECURITY_POLICY': 'Content-Security-Policy',
		'CONTENT_SECURITY_POLICY_REPORT_ONLY': 'Content-Security-Policy-Report-Only',
		'CONTENT_TYPE': 'Content-Type',
		'COOKIE': 'Cookie',
		'CRITICAL_CH': 'Critical-CH',
		'CROSS_ORIGIN_EMBEDDER_POLICY': 'Cross-Origin-Embedder-Policy',
		'CROSS_ORIGIN_OPENER_POLICY': 'Cross-Origin-Opener-Policy',
		'CROSS_ORIGIN_RESOURCE_POLICY': 'Cross-Origin-Resource-Policy',
		'DATE': 'Date',
		'DEVICE_MEMORY': 'Device-Memory',
		'DNT': 'DNT',
		'DOWNLINK': 'Downlink',
		'DPR': 'DPR',
		'EARLY_DATA': 'Early-Data',
		'ECT': 'ECT',
		'ETAG': 'ETag',
		'EXPECT': 'Expect',
		'EXPECT_CT': 'Expect-CT',
		'EXPIRES': 'Expires',
		'FORWARDED': 'Forwarded',
		'FROM': 'From',
		'HOST': 'Host',
		'IF_MATCH': 'If-Match',
		'IF_MODIFIED_SINCE': 'If-Modified-Since',
		'IF_NOT_MATCH': 'If-Not-Match',
		'IF_RANGE': 'If-Range',
		'IF_UNMODIFIED_SINCE': 'If-Unmodified-Since',
		'KEEP_ALIVE': 'Keep-Alive',
		'LAST_MODIFIED': 'Last-Modified',
		'LINK': 'Link',
		'LOCATION': 'Location',
		'MAX_FORWARDS': 'Max-Forwards',
		'NEL': 'NEL',
		'NO_VARY_SEARCH': 'No-Vary-Search',
		'OBSERVE_BROWSING_TOPICS': 'Observe-Browsing-Topics',
		'ORIGIN': 'Origin',
		'ORIGIN_AGENT_CLUSTER': 'Origin-Agent-Cluster',
		'PERMISSION_POLICY': 'Permission-Policy',
		'PRAGMA': 'Pragma',
		'PRIORITY': 'Priority',
		'PROXY_AUTHENTICATE': 'Proxy-Authenticate',
		'PROXY_AUTHORIZATION': 'Proxy-Authorization',
		'RANGE': 'Range',
		'REFERER': 'Referer',
		'REFERER_POLICY': 'Referer-Policy',
		'REFRESH': 'Refresh',
		'REPORT_TO': 'Report-To',
		'REPORTING_ENDPOINT': 'Reporting-Endpoint',
		'REPR_DIGEST': 'Repr-Digest',
		'RETRY_AFTER': 'Retry-After',
		'RTT': 'RTT',
		'SAVE_DATA': 'Save-Data',
		'SEC_BROWSING_TOPICS': 'Sec-Browsing-Topics',
		'SEC_CH_PREFERS_COLOR_SCHEME': 'Sec-CH-Prefers-Color-Scheme',
		'SEC_CH_PREFERS_REDUCED_MOTION': 'Sec-CH-Prefers-Reduced-Motion',
		'SEC_CH_PREFERS_REDUCED_TRANSPARENCY': 'Sec-CH-Prefers-Reduced-Transparency',
		'SEC_CH_UA': 'Sec-CH-UA',
		'SEC_CH_UA_ARCH': 'Sec-CH-UA-Arch',
		'SEC_CH_UA_BITNESS': 'Sec-CH-UA-Bitness',
		'SEC_CH_UA_FULL_VERSION': 'Sec-CH-UA-Full-Version',
		'SEC_CH_UA_MOBILE': 'Sec-CH-UA-Mobile',
		'SEC_CH_UA_MODEL': 'Sec-CH-UA-Model',
		'SEC_CH_UA_PLATFORM': 'Sec-CH-UA-Platform',
		'SEC_CH_UA_PLATFORM_VERSION': 'Sec-CH-UA-Platform-Version',
		'SEC_FETCH_DEST': 'Sec-Fetch-Dest',
		'SEC_FETCH_MODE': 'Sec-Fetch-Mode',
		'SEC_FETCH_SITE': 'Sec-Fetch-Site',
		'SEC_FETCH_USER': 'Sec-Fetch-User',
		'SEC_GPC': 'Sec-GPC',
		'SEC_PURPOSE': 'Sec-Purpose',
		'SEC_WEBSOCKET_ACCEPT': 'Sec-WebSocket-Accept',
		'SEC_WEBSOCKET_EXTENSIONS': 'Sec-WebSocket-Extensions',
		'SEC_WEBSOCKET_KEY': 'Sec-WebSocket-Key',
		'SEC_WEBSOCKET_PROTOCOL': 'Sec-WebSocket-Protocol',
		'SEC_WEBSOCKET_VERSION': 'Sec-WebSocket-Version',
		'SERVER': 'Server',
		'SERVER_TIMING': 'Server-Timing',
		'SERVICE_WORKER': 'Service-Worker',
		'SERVICE_WORKER_ALLOWED': 'Service-Worker-Allowed',
		'SERVICE_WORKER_NAVIGATION_PRELAOD': 'Service-Worker-Navigation-Prelaod',
		'SET_COOKIE': 'Set-Cookie',
		'SET_LOGIN': 'Set-Login',
		'SOURCEMAP': 'SourceMap',
		'SPECULATION_RULES': 'Speculation-Rules',
		'STRICT_TRANSPORT_SECURITY': 'Strict-Transport-Security',
		'SUPPORTS_LOADING_MODE': 'Supports-Loading-Mode',
		'TE': 'TE',
		'TIMING_ALLOW_ORIGIN': 'Timing-Allow-Origin',
		'TK': 'Tk',
		'TRAILER': 'Trailer',
		'TRANSFER_ENCODING': 'Transfer-Encoding',
		'UPGRADE': 'Upgrade',
		'UPGRADE_INSECURE_REQUESTS': 'Upgrade-Insecure-Requests',
		'USER_AGENT': 'User-Agent',
		'VARY': 'Vary',
		'VIA': 'Via',
		'VIEWPORT_WIDTH': 'Viewport-Width',
		'WANT_CONTENT_DIGEST': 'Want-Content-Digest',
		'WANT_REPR_DIGEST': 'Want-Repr-Digest',
		'WARNING': 'Warning',
		'WIDTH': 'Width',
		'WWW_AUTHENTICATE': 'WWW-Authenticate',
		'X_CONTENT_TYPE_OPTIONS': 'X-Content-Type-Options',
		'X_DNS_PREFETCH_CONTROL': 'X-DNS-Prefetch-Control',
		'X_FORWARDED_FOR': 'X-Forwarded-For',
		'X_FORWARDED_HOST': 'X-Forwarded-Host',
		'X_FORWARDED_PROTO': 'X-Forwarded-Proto',
		'X_FRAME_OPTIONS': 'X-Frame-Options',
		'X_PERMITTED_CROSS_DOMAIN_POLICIES': 'X-Permitted-Cross-Domain-Policies',
		'X_POWERED_BY': 'X-Powered-By',
		'X_ROBOTS_TAG': 'X-Robots-Tag',
		'X_XSS_PROTECTION': 'X-XSS-Protection',
	}.get(key, key) # TODO: replace _ to - and make uppper token's first character


def ParseRequestHeader(k: str, v: str) -> Any:
	parse = {
		# Common Headers
		'ACCEPT': ParseAccept(),
		'ACCEPT_ENCODING': ParseAcceptEncoding(),
		'CACHE_CONTROL' : ParseRequestCacheControl(),
		'CONNECTION': ParseString(),
		'DATE': ParseDate(),
		'KEEP_ALIVE': ParseKeepAlive(),
		'LINK': ParseLink(),
		'PRAGMA': ParseString(),
		'PRIORITY': ParsePriority(),
		'UPGRADE' : ParseUpgrade(),
		'VIA': ParseVia(),
		'WARNING': ParseWarning(),
		# Content Headers
		'CONTENT_DIGEST': ParseParameters(),
		'CONTENT_DISPOSITION': ParseStringWithParameters(paramsep=';'),
		'CONTENT_DPR': ParseFloat(),
		'CONTENT_ENCODING': ParseList(),
		'CONTENT_LANGUAGE': ParseList(),
		'CONTENT_LENGTH': ParseInteger(),
		'CONTENT_LOCATION': ParseString(),
		'CONTENT_RANGE': ParseContentRange(),
		'CONTENT_SECURITY_POLICY': ParseParameters(sep=';', paramsep=' '),
		'CONTENT_SECURITY_POLICY_REPORT_ONLY': ParseParameters(sep=';', paramsep=' '),
		'CONTENT_TYPE': ParseContentType(),
		'ETAG': ParseETag(),
		'LAST_MODIFIED': ParseDate(),
		'REPR_DIGEST': ParseParameters(),
		'TRAILER': ParseString(),
		'TRANSFER_ENCODING': ParseList(),
		'WANT_CONTENT_DIGEST': ParseParameters(),
		'WANT_REPR_DIGEST': ParseParameters(),
		# Request Headers
		'ACCEPT_LANGUAGE': ParseAcceptLanguage(),
		'ALT_USED': ParseAltUsed(),
		'AUTHORIZATION': ParseAuthorization(),
		'COOKIE': ParseCookie(),
		'DEVICE_MEMORY': ParseFloat(),
		'DNT': ParseInteger(),
		'DOWNLINK': ParseFloat(),
		'DPR': ParseFloat(),
		'EARLY_DATA': ParseInteger(),
		'ECT': ParseString(),
		'EXPECT': ParseString(),
		'FORWARDED': ParseList(fetch=ParseParameters(sep=';')),
		'FROM': ParseString(),
		'HOST': ParseString(),
		'IF_MATCH': ParseList(),
		'IF_MODIFIED_SINCE': ParseDate(),
		'IF_NONE_MATCH': ParseList(),
		'IF_RANGE': ParseIfRange(),
		'IF_UNMODIFIED_SINCE': ParseDate(),
		'MAX_FORWARDS': ParseInteger(),
		'ORIGIN': ParseString(),
		'PROXY_AUTHORIZATION': ParseProxyAuthorization(),
		'RANGE': ParseRange(),
		'REFERER': ParseString(),
		'RTT': ParseFloat(),
		'SAVE_DATA': ParseString(),
		'SEC_BROWSING_TOPICS': ParseString(),
		'SEC_CH_PREFERS_COLOR_SCHEME': ParseString(),
		'SEC_CH_PREFERS_REDUCED_MOTION': ParseString(),
		'SEC_CH_PREFERS_REDUCED_TRANSPARENCY': ParseString(),
		'SEC_CH_UA': ParseSecCHUA(),
		'SEC_CH_UA_ARCH': ParseString(),
		'SEC_CH_UA_BITNESS': ParseInteger(),
		'SEC_CH_UA_FULL_VERSION': ParseString(),
		'SEC_CH_UA_FULL_VERSION_LIST': ParseSecCHUAFullVersion(),
		'SEC_CH_UA_MOBILE': ParseBoolean(true='?1'),
		'SEC_CH_UA_MODEL': ParseString(),
		'SEC_CH_UA_PLATFORM': ParseString(),
		'SEC_CH_UA_PLATFORM_VERSION': ParseString(),
		'SEC_FETCH_DEST': ParseString(),
		'SEC_FETCH_MODE': ParseString(),
		'SEC_FETCH_SITE': ParseString(),
		'SEC_FETCH_USER': ParseBoolean(true='?1'),
		'SEC_GPC': ParseBoolean(true='1'),
		'SEC_PURPOSE': ParseString(),
		'SERVICE_WORKER': ParseString(),
		'SERVICE_WORKER_NAVIGATION_PRELOAD': ParseString(),
		'TE': ParseTE(),
		'UPGRADE_INSECURE_REQUESTS': ParseBoolean(true='1'),
		'USER_AGENT': ParseString(),
		'VIEWPORT_WIDTH': ParseInteger(),
		'WIDTH': ParseInteger(),
		'X_FORWARDED_FOR': ParseList(),
		'X_FORWARDED_HOST': ParseString(),
		'X_FORWARDED_PROTO': ParseString(),
		# Response Headers
		# CORS Headers
		# WebSocket Headers
		# None Classified Headers
	}.get(k.replace('-','_').upper(), ParseString())
	return parse(v)
